  version: '3.2'
  services:
    postgres:
        image: postgres:12
        container_name: sber_postgres
        environment:
            - POSTGRES_PASSWORD=postgres
        ports:
            - '5433:5432'
        volumes:
            - ./db/:/var/lib/postgresql/data
    app:
        build: app/
        container_name: sber_app
        depends_on:
            - postgres
        ports:
            - '5000:8080'
        volumes:
            - ./app:/app